# Colors Doric-Marble
[colors.normal]
black = '#dfdfdf'
red = '#a01010'
green = '#106710'
yellow = '#60400f'
blue = '#103077'
magenta = '#700d50'
cyan = '#005355'
white = '#202020'
[colors.bright]
black = '#dfdfdf'
red = '#a01010'
green = '#106710'
yellow = '#60400f'
blue = '#103077'
magenta = '#700d50'
cyan = '#005355'
white = '#202020'
[colors.cursor]
cursor = '#403030'
text = '#ededed'
[colors.primary]
background = '#ededed'
foreground = '#202020'
[colors.selection]
background = '#b0b0b0'
text = '#202020'
